### ISSUE TITLE
Provide docker image

### ISSUE THREAD

**Issue by avdeev** [antonk52/swaggerlint#17]
Like https://hub.docker.com/r/widerin/alpine-eslint

**Comment by antonk52** [comment]
Thank you for the great idea! Will get on it soon👍

**Comment by antonk52** [comment]
I've published a a public swaggerlint docker image, I am new to docker so not too sure if everything works as expected. Can you please verify that it works as you expect and I will happily add it to readme

https://hub.docker.com/repository/docker/antonk52/alpine-swaggerlint

**Comment by avdeev** [comment]
Works fine for me!

**Comment by antonk52** [comment]
Awesome, then I'll be adding it to the readme. Thank you!
